config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "jobs#index"

  resources :jobs do
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :hide
        post :publish
      end

      resources :resumes
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true

  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}

  def hide!
    self.is_hidden = true
    self.save
  end

  def publish!
    self.is_hidden = false
    self.save
  end

  scope :published, -> { where(:is_hidden => false) }
  scope :recent, -> { order("created_at DESC") }

  has_many :resumes
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :content, presence: true

  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def is_admin?
    is_admin
  end

  has_many :resumes

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :required_is_admin
  layout "admin"


  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden)
  end



end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :required_is_admin

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order("created_at DESC")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def required_is_admin
    if !current_user.is_admin?
      redirect_to root, notice: "You are not admin"
    end
  end
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  def index
    @jobs = case params[:order]
            when "by_lower_bound"
             Job.published.order("wage_lower_bound DESC")
            when "by_upper_bound"
             Job.published.order("wage_upper_bound DESC")
            else
             Job.published.recent
            end
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = "Job created"
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      flash[:notice] = "Job Updated"
      redirect_to jobs_path
    else
      render :new
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy
    flash[:alert] = "Job Deleted"
      redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden)
  end


end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save(resume_params)
      flash[:notice] = " Resume Submitted"
        redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "welcome"
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
     if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
     else
      content_tag(:span, "", :class => "fa fa-globe")
     end
   end

end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.erb
<h1> Edit Job </h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound %>
<%= f.input :wage_upper_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>


<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("Add a Job", new_admin_job_path, class: "btn btn-primary") %>
</div>
<br><br><br>

<table class="table table-bordered">
  <thead>
      <tr>
          <th> Title </th>
          <th> Resume </th>
          <th> Description</th>
          <th> Time </th>
          <th> Option</th>
      </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
          <td>
            <%= render_job_status(job) %>
            <%= link_to(job.title, job_path(job)) %> </td>
          <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
          <td> <%= job.description %> </td>
          <td> <%= job.created_at.to_s(:long) %></td>
          <td>
            <%= link_to("Edit", edit_admin_job_path(job), class: "btn btn-sm btn-primary") %>
            <%= link_to("Delete", admin_job_path(job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger") %>
            <% if job.is_hidden %>
              <%= link_to("Publish", publish_admin_job_path(job), method: :post, :class => "btn btn-sm btn-success") %>
            <% else %>
              <%= link_to("Hide", hide_admin_job_path(job), method: :post, :class => "btn btn-sm btn-success") %>
            <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/jobs/new.html.erb
<h1> New Job </h1>

<%= simple_form_for [:admin, @job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound %>
<%= f.input :wage_upper_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> <%= resume.user.email %></h3>
  </div>

  <div class="panel-body">
    <div class="content">
      <%= simple_format(resume.content) %>
    </div>

    <hr>

    <% if resume.attachment.present? %>
      <i class="fa fa-paperclip"></i>
      <%= link_to("Download resume", resume.attachment_url) %>
    <% else %>
      No Attachment
    <% end %>

  </div>
</div>

app/views/admin/resumes/index.html.erb
<h2> <%= @job.title %> - Resume List</h2>
<hr>

<%= render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="margin-top: 100px;">
  <p class="text-center">
    Copyright ©2017<br>
    Design by
    <a href="http://justincs.logdown.com/" target=_new>Justin Ng </a>
  <p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
        <!-- Brand and toggle get grouped together for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="/"> Job Listing 6</a>
        </div>

        <!-- Collect links, form & other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
                <li><%= link_to("Signup", new_user_registration_path) %></li>
                <li><%= link_to("Login", new_user_session_path) %></li>
            <% else %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                    <% if current_user.is_admin %>
                      <li> <%= link_to("Admin Panel", admin_jobs_path) %> </li>
                    <% end %>
                      <li>
                        <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
                      </li>
                    </ul>
                </li>
            <% end %>
          </ul>
        </div>
        <!-- /collapse end -->
  </div>
  <!-- /navbar end -->
</nav>

app/views/jobs/edit.html.erb
<h1> Edit Job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound %>
<%= f.input :wage_upper_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/jobs/index.html.erb
<div class="dropdown pull-right">
  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" >
    Option<a class="caret"></a>
  </button>
  <ul class="dropdown-menu" >
    <li> <%= link_to("wage_lower_bound", jobs_path(:order => "by_lower_bound")) %></li>
    <li> <%= link_to("wage_upper_bound", jobs_path(:order => "by_upper_bound")) %></li>
    <li> <%= link_to("time", jobs_path) %></li>
  </ul>
</div>
<br><br><br>

<table class="table table-bordered">
  <thead>
      <tr>
          <th> Title </th>
          <th> Wage_lower_bound</th>
          <th> wage_upper_bound </th>
          <th> Time</th>
      </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
          <td> <%= link_to(job.title, job_path(job)) %> </td>
          <td> <%= job.wage_lower_bound %> </td>
          <td> <%= job.wage_lower_bound %> </td>
          <td> <%= job.created_at.to_s(:long) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1> New Job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound %>
<%= f.input :wage_upper_bound %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<%= simple_format @job.description %>

<div class="text-center" style="text-decoration: underline">
  <h2> <%= link_to("Submit Resume", new_job_resume_path(@job)) %></h2> 
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>

      <div class="row">
        <div class="col-md-2">
          <div class="nav nav-pills nav-stacked">
            <li class="active"><%= link_to("Jobs", admin_jobs_path, class: "btn btn-primary") %></li>
          </div>
        </div>

        <div class="col-md-10">
          <%= yield %>
        </div>

    </div>


    <%= render "common/footer" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div class="container-fluid">
          <%= render "common/navbar" %>
          <%= render "common/flashes" %>
          <%= yield %>
        </div>


        <%= render "common/footer" %>

  </body>
</html>

app/views/resumes/new.html.erb
<h2> Submit resume for <%= @job.title %></h2>

<%= simple_form_for [@job, @resume] do |f| %>

<%= f.input :content %>
<%= f.input :attachment %>

<%= f.submit "Submit", class: "btn btn-success" %>

<% end %>

app/views/welcome/index.html.erb
 
  <h1> Welcome </h1>